### PR TITLE
upd: layout-adjustments

### PR DESCRIPTION
**Pull request by tsudd**
Made adjustments in layout according to your recommendations and more.

### CODE REVIEW

**Review by katetushkan — DISMISSED** [review]
Pls, commit to ur existing pr, cuz it's difficult to check

**Comment by tsudd** [comment]
Previous PR will be continued...

**Comment by tsudd** [comment]
Unfortunately, I'm not able to reopen merged PR with the previous lab: [it was fully closed](https://stackoverflow.com/questions/12674304/github-reopening-a-merged-pull-request)
kindly ask you to check these changes here. In the future, will continue adjustments in the same PR.

**Review by katetushkan — APPROVED** [review]
`10`

**Comment by katetushkan** [comment]
add name to read.me

**Pull request merged**
